export const LANGUAGE = "en";
export const PAGINATION_PARAMS_LIMIT = 20;
export const WINDOWS_RESIZE_DEBOUNCE_TIME = 500;
export const SEARCH_DEBOUNCE_TIME = 500;
export const DEFAULT_PATH = "pokemon";
export const ERROR_PATH = "error";
export const DETAIL_ROUTE_PARAM = "nameOrId";
export const NAVIGATE_STATE_ERROR_MESSAGE = "errorMessage";
export const DEFAULT_ERROR_MESSAGE = "The page you are trying to access does not exist. It may have been removed, had its name changed, or is temporarily unavailable.";
