export const DEFAULT_FONT_SIZE = 16;
export const CARD_GAP_TAILWIND_CSS = 4;
export const CARD_WIDTH_TAILWIND_CSS = 64;
export const CARD_HEIGHT_TAILWIND_CSS = 96;
export const CARD_GAP_PX = CARD_GAP_TAILWIND_CSS / 4 * DEFAULT_FONT_SIZE;
export const CARD_WIDTH_PX = CARD_WIDTH_TAILWIND_CSS / 4 * DEFAULT_FONT_SIZE;
export const CARD_HEIGHT_PX = CARD_HEIGHT_TAILWIND_CSS / 4 * DEFAULT_FONT_SIZE;
